# Use the official Bun image as the base image
FROM oven/bun:latest

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and bun.lockb if available to install dependencies first (better caching)
COPY package.json ./

# Install dependencies using Bun
RUN bun install

# Copy the rest of the application code to the working directory
COPY . .

# Build the Next.js application
RUN bun next build

# Expose the port your application will run on (for Next.js, default is 3000)
EXPOSE 3000

# Set the environment variable to production
ENV NODE_ENV=production

# Start the Next.js application using Bun
CMD ["bun", "next", "start", "-p", "3031"]
