apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-matrix-api
  namespace: application
spec:
  replicas: 5
  selector:
    matchLabels:
      app: go-matrix-api
  template:
    metadata:
      labels:
        app: go-matrix-api
    spec:
      containers:
      - name: go-matrix-api
        image: go-matrix-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3030
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"