apiVersion: v1
kind: Service
metadata:
  name: matrix-go-app-service
spec:
  type: NodePort
  selector:
    app: matrix-go-app
  ports:
    - protocol: TCP
      port: 3030
      targetPort: 3030
      nodePort: 30001 # This will expose the service on localhost:30001