apiVersion: v1
kind: Service
metadata:
  name: go-matrix-api-service
spec:
  type: NodePort
  selector:
    app: go-matrix-api
  ports:
    - protocol: TCP
      port: 3030
      targetPort: 3030
      nodePort: 30001 # This will expose the service on localhost:30001